// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0lesNsqsnNdGaIzQtCibAP4OlA8xsRBg',
    appId: '1:726054875301:web:160fc9f5155c3e8a3a1d4c',
    messagingSenderId: '726054875301',
    projectId: 'sugenix-8e308',
    authDomain: 'sugenix-8e308.firebaseapp.com',
    storageBucket: 'sugenix-8e308.firebasestorage.app',
    measurementId: 'G-ZZ3KSKW3K5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_pXzCP8ZJLotaiWbxKh0pfgZMQNgl9LM',
    appId: '1:726054875301:android:08ef47bfb75937483a1d4c',
    messagingSenderId: '726054875301',
    projectId: 'sugenix-8e308',
    storageBucket: 'sugenix-8e308.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqtZBzKDyf6baHjdtFK6s_HDwvLuRA2wM',
    appId: '1:726054875301:ios:1959dfc6b13392e53a1d4c',
    messagingSenderId: '726054875301',
    projectId: 'sugenix-8e308',
    storageBucket: 'sugenix-8e308.firebasestorage.app',
    iosBundleId: 'com.example.sugenix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqtZBzKDyf6baHjdtFK6s_HDwvLuRA2wM',
    appId: '1:726054875301:ios:1959dfc6b13392e53a1d4c',
    messagingSenderId: '726054875301',
    projectId: 'sugenix-8e308',
    storageBucket: 'sugenix-8e308.firebasestorage.app',
    iosBundleId: 'com.example.sugenix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0lesNsqsnNdGaIzQtCibAP4OlA8xsRBg',
    appId: '1:726054875301:web:e8ad6d8d55e459583a1d4c',
    messagingSenderId: '726054875301',
    projectId: 'sugenix-8e308',
    authDomain: 'sugenix-8e308.firebaseapp.com',
    storageBucket: 'sugenix-8e308.firebasestorage.app',
    measurementId: 'G-PM4TT26SZY',
  );
}
